DT-22: Initial CloudFront and ALB setup
communitiesuk/delta-common-infrastructure pull request #6
Opened 2022-09-12 12:43 UTC by BenRamchandani

* Created EC2 instance running Nginx for testing purposes
* Set up ALB and CloudFront pointing at Nginx box
* Includes basic WAF rules, access logs and CloudFront -> ALB authentication with header

Things left to discuss/do:
* Set up domains, both for CloudFront and the ALB, then switch the ALB over to HTTPS
* Set up custom error pages if we want those?
* If we want a maintenance mode where the ALB returns a fixed response, then set that up

2022-09-23 15:04 UTC, BenRamchandani commented
I'll make changes in https://github.com/communitiesuk/delta-common-infrastructure/pull/9 to put Jaspersoft behind CloudFront, so probably ignore this for now

2022-09-26 13:50 UTC, hugh-emerson commented on terraform/modules/cloudfront/cloudfront.tf
> -    Environment = "production"
We already have a default tag for "environment", no?

2022-09-26 13:52 UTC, hugh-emerson approved these changes
Looks good.

After jaspersoft is up and running as an example origin, we can bin the nginx stuff?

2022-09-26 13:53 UTC, hugh-emerson requested changes
Oh actually, just noticed this is missing aws_shield_protection for the cloudfront distribution

2022-09-26 15:29 UTC, BenRamchandani commented
> After jaspersoft is up and running as an example origin, we can bin the nginx stuff?

Yes, definitely, it's just to have something to test with

2022-09-26 15:30 UTC, BenRamchandani commented
> Oh actually, just noticed this is missing aws_shield_protection for the cloudfront distribution. Sorry it wasn't mentioned on the ticket - adding it now.

As discussed - leaving this for DT-63

2022-09-26 15:37 UTC, BenRamchandani commented
Test plan is failing because I'm messing around and have a bunch of us-east-1 stuff in the state. I'd like to get this merged anyway as the Jaspersoft branch builds on top of it.

2022-09-27 15:28 UTC, merged